import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useEffect } from 'react';
import { RecoilRoot } from 'recoil';
import { getAnalytics } from '../lib/firebase';

const App = ({ Component, pageProps }: AppProps) => {
  useEffect(() => {
    getAnalytics();
  }, []);
  return (
    <RecoilRoot>
      <Head>
        <title>{process.env.NEXT_PUBLIC_SITE_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </RecoilRoot>
  );
};
export default App;
